type: object
properties:
    Id: UUID
    Name: string
    Description: string
    Price:
        type: number
        multipleOf: 0.01
    DeliveryPrice:
        type: number
        multipleOf: 0.01